### ISSUE TITLE
Navigation: Basic Sidesheet Component

### ISSUE THREAD

**Issue by mmmoore1313** [specollective/open-design-system#23]
A developer wants a basic Sidesheet (left/right) component.
ex:
```HTML
<div  class="sidescroll">
</div>
```
```CSS
div.sidescroll {
  overflow: auto;
  white-space: nowrap;
}
```
suggested name: basic-sidescroll
